theme: jekyll-theme-slate
title: [My Portfolio]
description: [Trace of effort]
<a class="zip_download_link" href="https://github.com/pages-themes/slate/zipball/master">Download this project as a .zip file</a>
